#Gateway Cluster Configuration State (Auto-Restored on boot)
#Fri Jun 26 12:18:37 ICT 2026
fwEnabled=false
fwLen=1000
fwLim=100
lsEnabled=true
lsMax=5
lsMin=50.0
swEnabled=false
swLen=1000
swLim=100
tbCap=1000
tbEnabled=true
tbRefill=10.0
